# Generated by Django 3.2.12 on 2023-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='pics')),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
