# Generated by Django 3.2.12 on 2023-03-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20230323_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
